project:
  type: website

website:
  title: "bioinformaticsTrainingProgramme"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - portfolio.qmd
        text: Workshop portfolio

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



