project:
  type: website

website:
  title: "Bioinformatics Training Programme"
  favicon: assets/img/nesi_ga.png
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Training Programme Overview
      - href: portfolio.qmd
      - href: about.qmd
      

format:
  html:
    theme: 
        light: flatly
        dark: darkly
    css: styles.css
    toc: true



